name: ci-mlflow-project

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "MLProject/**"
      - ".github/workflows/**"

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # INI KUNCI: pastikan conda beneran siap dan PATH beres,
      # supaya "source activate <env>" dari MLflow tidak error.
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          miniconda-version: "latest"
          python-version: "3.12"
          auto-activate-base: true

      - name: Install MLflow (runner env)
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0

      - name: Debug - show modelling.py section
  	working-directory: MLProject
  	run: |
    	  echo "=== modelling.py path ==="
          pwd
          ls -la
          echo "=== grep log_param(data_path) ==="
          grep -n 'log_param("data_path"' -n modelling.py || true
          echo "=== modelling.py around lines 120-160 ==="
          nl -ba modelling.py | sed -n '120,170p'


      - name: Run MLflow Project (conda)
        shell: bash -l {0}
        working-directory: MLProject
        env:
          # Kalau mau logging ke DagsHub, set secrets ini.
          # Kalau tidak di-set, modelling.py akan fallback ke local ./mlruns
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
          MLFLOW_EXPERIMENT_NAME: creditscoring-MSML
        run: |
          mlflow run . \
            -P data_path=creditscoring_preprocessing/creditscoring_preprocessed.csv \
            -P target_col=target

      - name: Upload local MLflow runs as artifact (if exists)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: MLProject/mlruns
